### ISSUE TITLE
Breaks Play Integrity API for some devices (needs to be tested for >v1.15.0)

### ISSUE THREAD

**Issue by pmsobrado** [j-hc/zygisk-detach#18] opened 2023-12-23 16:19 UTC
**Screenshot of Play Store page of the app you are trying to detach:**

Not applicable.

**Screenshot of the helper CLI showing detached apps (from Option 2):**

Not applicable.

**Logs taken with `su -c logcat -s "zygisk-detach" > /sdcard/log.txt`:**

Not applicable.

I used this module to detach an app. After that, the Play Integrity API request from Play store (in developer tools/options) fails with error -100 (internal error). After trying some stuff I checked logcat, and found an error trying to read the detached app from somewhere, some database I guess. The app had the first two characters modified to unknown ones, which I guess is the method this module uses to detach.

In any case, this seesm to break Play Integrity API request from official Play store app.

**Comment by j-hc** [comment] 2023-12-23 17:13
cant reproduce. even if that was the case i cant fix it. i already did whats possible to not break play integrity.

**Comment by pmsobrado** [comment] 2023-12-23 17:20
It was a weird coincidence I guess...

**Comment by yuzamei2854** [comment] 2024-01-16 02:24
I have the same issue, after enabling the module and rebooting the system, the issue with Play Integrity API starts happening, i tried using SPIC and this error shows up:

![20240115_231819](https://github.com/j-hc/zygisk-detach/assets/141790911/66931168-2a91-432d-8760-e67ef26b5080)

For now, SafetyNet works fine.

I'm using a Samsung phone with a custom ROM and Magisk.

**Comment by pmsobrado** [comment] 2024-01-16 07:51
Even without reboot, the moment I detach, I get a -100 error. The moment I reattach, the error is gone.

In logcat I saw an error with weird characters on the detached package name, my guess is this module breaks the package name in a way that google play does not detect it, making the app detached, but the package name change with weird characters also breaks integrity api call, for some reason.

Issue still happens to me.

**Comment by j-hc** [comment] 2024-01-16 09:51
try v1.10.0, it does not hook the process where the integrity evaluation happens anymore.

**Comment by pmsobrado** [comment] 2024-01-16 10:03
@j-hc Sorry, still the same, here's the log:

![imagen](https://github.com/j-hc/zygisk-detach/assets/17699739/85be695d-6e62-48a8-a3ca-b1c153986c35)

Let's see how it goes for @yuzamei2854

**Comment by yuzamei2854** [comment] 2024-01-16 15:50
Hi, forgive me if I'm not able to pass on possible information, I'm still new to root and Magisk. 

The problem still persists after the v1.10.0 update, I did the same test as the OP about detach and reattach, and I can confirm that when the application is detached, the error -100 starts to appear, after reattaching the error disappears.

As I still don't know how to get logs, I used the same app as the OP, here's a screenshot of a part I suspect from the log.
![20240116_124139](https://github.com/j-hc/zygisk-detach/assets/141790911/e7cf2c4f-6dc4-4792-a82d-2ce89f1401d4)

**Comment by j-hc** [comment] 2024-01-16 17:06
whats output of this on termux:
`ps -A | grep vending`

**Comment by pmsobrado** [comment] 2024-01-16 17:34
Nothing, apparently:

![IMG_20240116_183341](https://github.com/j-hc/zygisk-detach/assets/17699739/800e9711-2201-4649-948b-bd7e0d7abf58)

**Comment by j-hc** [comment] 2024-01-16 17:45
it should be run with su:
su -c ps -A | grep vending

**Comment by pmsobrado** [comment] 2024-01-16 17:51
![IMG_20240116_184946](https://github.com/j-hc/zygisk-detach/assets/17699739/15370e78-f3d1-47f2-8c11-f2a558be180a)

**Comment by yuzamei2854** [comment] 2024-01-16 18:30
> it should be run with su: su -c ps -A | grep vending

![20240116_152859](https://github.com/j-hc/zygisk-detach/assets/141790911/cd420873-e4c7-4cc8-8987-126c59efc332)

**Comment by pmsobrado** [comment] 2024-01-16 19:51
Hmm, still issues when the package name is not recognized...

**Comment by pmsobrado** [comment] 2024-01-29 09:53
BTW, in case it helps. I'm on MIUI 12 / Android 10 (xiaomi.eu rom).

**Comment by j-hc** [comment] 2024-01-31 14:28
@pmsobrado @yuzamei2854 try this one
[zygisk-detach-v1.11.0t.zip](https://github.com/j-hc/zygisk-detach/files/14112893/zygisk-detach-v1.11.0t.zip)

**Comment by pmsobrado** [comment] 2024-01-31 17:35
@j-hc Still no dice 😩

![IMG_20240131_183341](https://github.com/j-hc/zygisk-detach/assets/17699739/f833ef78-73b9-4112-98b0-d6f4f3ab4238)

Same -100 error:

![Uploading IMG_20240131_183524.jpg…]()

**Comment by j-hc** [comment] 2024-01-31 22:55
@pmsobrado how about this one
[zygisk-detach-v1.11.0t.zip](https://github.com/j-hc/zygisk-detach/files/14118138/zygisk-detach-v1.11.0t.zip)

**Comment by pmsobrado** [comment] 2024-02-01 10:08
It works! How did you do it?

**Comment by j-hc** [comment] 2024-02-01 13:22
> It works! How did you do it?

by using a hackish way to return a fake app's info. it works for you but will crash for other android versions.

**Comment by pmsobrado** [comment] 2024-02-01 13:24
That's weird... I do have Android 10 and MIUI 12, but Play Store version should be the same, or similar to modern phones, right? Why this different behaviour?

**Comment by j-hc** [comment] 2024-02-01 14:30
> That's weird... I do have Android 10 and MIUI 12, but Play Store version should be the same, or similar to modern phones, right? Why this different behaviour?

because im not hooking play store but libbinder.
im still not yet sure about the proper solution.

> BTW, the app shows as "disabled" on Play Store, is that a part of the hackish ways?

yes

**Comment by pmsobrado** [comment] 2024-02-01 15:13
Well, if you need testing, logs or want me to debug something, please ask :)

**Comment by yuzamei2854** [comment] 2024-02-04 03:01
> @pmsobrado @yuzamei2854 try this one [zygisk-detach-v1.11.0t.zip](https://github.com/j-hc/zygisk-detach/files/14112893/zygisk-detach-v1.11.0t.zip)



> @pmsobrado @yuzamei2854 try this one [zygisk-detach-v1.11.0t.zip](https://github.com/j-hc/zygisk-detach/files/14112893/zygisk-detach-v1.11.0t.zip)

Not working, still the same error.

**Comment by yuzamei2854** [comment] 2024-02-04 03:01
> @pmsobrado how about this one [zygisk-detach-v1.11.0t.zip](https://github.com/j-hc/zygisk-detach/files/14118138/zygisk-detach-v1.11.0t.zip)

Working on A9.

**Comment by pmsobrado** [comment] 2024-02-05 07:30
So I guess older versions of Android need different methods... but I still don't get it, isn't Play Store app version the same as on recent phones? Shouldn't this only affect Play Store app, and not anything of the Android system/ROM?

**Comment by j-hc** [comment] 2024-02-05 13:02
> So I guess older versions of Android need different methods... but I still don't get it, isn't Play Store app version the same as on recent phones? Shouldn't this only affect Play Store app, and not anything of the Android system/ROM?

like i said play store version is irrelevant. zygisk-detach hooks binder driver of the kernel which changes across android versions.
i have the fix, just dont have time to experiment yet. for now you can keep using the latest test version i sent.

**Comment by pmsobrado** [comment] 2024-02-05 13:04
Yes, don't worry, take all the time you need. I just though you we're binding some Play Store process (on normal versions of your module, not these latest test ones) renaming packages on some db relative to Play Store, without affecting the system.

**Comment by N0nd** [comment] 2024-02-09 20:36
I also ran into this problem on Android 9
https://github.com/chiteroman/PlayIntegrityFix/issues/254#issuecomment-1936507780

**Comment by MrManinBlack1337** [comment] 2024-02-14 04:59
I am getting the same issue, tested with release and all tests versions all break integrity API.
My rom is android 10 non-MIUI, Xiaomi Redmi Note 7

**Comment by j-hc** [comment] 2024-02-23 16:40
ok i decided on a solution. new test build here: 
[zygisk-detach-v1.12.0t.zip](https://github.com/j-hc/zygisk-detach/files/14387732/zygisk-detach-v1.12.0t.zip)

if working fine, i will merge the changes.

@yuzamei2854 @pmsobrado

**Comment by MrManinBlack1337** [comment] 2024-02-23 16:54
The newest test version works for me, play integrity remained intact! Thank you

**Comment by j-hc** [comment] 2024-02-23 17:08
aight merged the changes

**Comment by pmsobrado** [comment] 2024-02-23 17:19
Works for me too.

**Comment by j-hc** [comment] 2024-03-26 22:34
i reverted the fix as it doesnt stop play store from updating detached apps: https://github.com/j-hc/zygisk-detach/issues/37
users with affected play integrity can keep using v1.13.0 until i implement another fix

**Comment by j-hc** [comment] 2024-03-28 15:20
here is a test module for those who get integrity error in v1.14.0

[zygisk-detach-v1.15.0t.zip](https://github.com/j-hc/zygisk-detach/files/14791724/zygisk-detach-v1.15.0t.zip)

**Comment by j-hc** [comment] 2024-07-25 12:52
closing the issues as nobody reported anything

**Closed by j-hc** 2024-07-25 12:52 UTC
